### ISSUE TITLE
Compilation broken with PackageCompiler 2.x

### ISSUE THREAD

**Issue by doorisajar** [harris-chris/Jot.jl#24]
Sample output from running `create_local_image(some_responder; package_compile = true)`:

```
Step 20/20 : RUN julia init.jl
 ---> Running in e228ad12679e
    Updating registry at `/var/runtime/julia_depot/registries/General`
   Resolving package versions...
   Installed RelocatableFolders ─ v0.1.3
   Installed Scratch ──────────── v1.1.0
   Installed PackageCompiler ──── v2.0.1
    Updating `/var/runtime/julia_depot/environments/v1.6/Project.toml`
  [9b87118b] + PackageCompiler v2.0.1
    Updating `/var/runtime/julia_depot/environments/v1.6/Manifest.toml`
  [9b87118b] + PackageCompiler v2.0.1
  [05181044] + RelocatableFolders v0.1.3
  [6c6a2e73] + Scratch v1.1.0
Precompiling project...
  ✓ Scratch
  ✓ RelocatableFolders
  ✓ PackageCompiler
  3 dependencies successfully precompiled in 2 seconds (73 already precompiled)
ERROR: LoadError: UndefKeywordError: keyword argument sysimage_path not assigned
```

If I instead edit the line of `init.jl` that adds PackageCompiler as follows:

```
Pkg.add(name="PackageCompiler",version="1.7.7")
```
And then manually run `docker build --rm --iidfile id --tag image path`, it works. 

Re-running `create_local_image` makes a new `init.jl`, though, so that fails.

PackageCompiler 2.x does have breaking changes: https://julialang.github.io/PackageCompiler.jl/dev/index.html#Upgrading-from-PackageCompiler-1.0.

I've used PackageCompiler 1.x before, but I'm not sure what `sysimage_path` should be set to in this context for compatibility with 2.x. Depending on 1.x by editing `[get_init_script](https://github.com/harris-chris/Jot.jl/blob/c5c7eac8b99fb0e998757e5cbe7a5f59c2d40391/src/Scripts.jl#L85)` would be a temporary workaround.

**Comment by harris-chris** [comment]
Hello - thanks for pointing this out - yes, it does seem to be an issue with the breaking changes in `PackageCompiler.jl`. The `replace_default` parameter in `create_sysimage` has been phased out, and you now have to specify a path for the new sysimage. I've just run the test suite with PackageCompiler v2, but the run-time of a compiled function is actually slower than an uncompiled function, so either I'm using it wrong or it has changed in some important way. For the time being I've pushed a new version that pins `PackageCompiler` to v1. Please let me know if that works any better for you.

**Comment by doorisajar** [comment]
That works, thanks! I'd done the same thing via `dev Jot` but having it on main is helpful to make future updating easier.

**Comment by harris-chris** [comment]
Great, glad to hear that. I'm sure the performance regression is just me misusing it somehow. I'll figure it out in due course and then switch Jot over to v2.
