### ISSUE TITLE
fails on `push_to_ecr!` (problem parsing output of `aws ecr describe-repositories`?)

### ISSUE THREAD

**Issue by onlyjsmith** [harris-chris/Jot.jl#27]
I'm following the first example (here)[https://harris-chris.github.io/Jot.jl/stable/], and I get an issue at step #5, trying to run `remote_image = push_to_ecr!(local_image)`:

```
julia> remote_image = push_to_ecr!(local_image)
Login Succeeded

...

ERROR: ArgumentError: invalid JSON at byte position 365 while parsing type String: ExpectedOpeningQuoteChar
            "createdAt": 1622815198.0,
```

I think it's trying to parse the output of `aws ecr describe-repositories` into a `ECRRepo` struct, but the types seem not quite compatible: the `createdAt` value should be some kind of number?

**Comment by onlyjsmith** [comment]
My fault! Was using an older version of AWS CLI - have just upgraded, and the output from `aws ecr describe-repositories` now has `createdAt` as a string...

Btw - Jot is neat, thanks for the package!

**Comment by harris-chris** [comment]
Great - glad it's working for you!
