### ISSUE TITLE
Reusing Images

### ISSUE THREAD

**Issue by mrufsvold** [harris-chris/Jot.jl#46]
I can't quite tell from the documentation if there's already structures for doing this. 

Let's say I have a package that has 5 different functions that I want to turn into Lambda functions. I'm aware that I could have one top level function that switches based on an input parameter, But it's nice to have separate functions with separate identities. However, I prefer not to pay for compiling separate images and storing separate images for each of these functions when all I really need is one image with multiple entry points. 

Is that supported in Jot.jl?

**Comment by harris-chris** [comment]
Hello - yes, I can relate to that situation myself. It isn't so much that
this isn't supported in Jot.jl, more that it's not supported in AWS Lambda
at all. There's a section in the documentation on this, but it just
suggests what you're trying to avoid:
https://harris-chris.github.io/Jot.jl/stable/Guide/#Working-around-the-one-function-per-container-limit

**Comment by mrufsvold** [comment]
Ah! Alright! Thanks for pointing me to the docs.
